
services:
  db:
    image: postgres:16
    container_name: portal_postgres
    restart: always
    environment:
      POSTGRES_DB: portal_de_servicos_de_inteligencia_de_dados
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 181059
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: portal_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=portal_de_servicos_de_inteligencia_de_dados
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=181059
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data:
